name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ec2-16-16-92-145.eu-north-1.compute.amazonaws.com
      EC2_USER: ubuntu
      EC2_APP_DIR: /var/www/myapp
      APP_SERVICE_NAME: my-fastapi

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: DNS preflight
        run: getent ahosts "$EC2_HOST"

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 15 "$EC2_HOST" >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=yes "$EC2_USER@$EC2_HOST" \
            "echo '✅ Connected to EC2:' $(hostname)"

      - name: Ensure target directory exists
        run: |
          ssh -o StrictHostKeyChecking=yes "$EC2_USER@$EC2_HOST" \
            "mkdir -p '$EC2_APP_DIR/releases/latest'"

      - name: Rsync repo to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=yes -o ConnectTimeout=30" \
            ./ "$EC2_USER@$EC2_HOST:$EC2_APP_DIR/releases/latest"

      - name: Restart FastAPI service
        run: |
          ssh -o StrictHostKeyChecking=yes "$EC2_USER@$EC2_HOST" \
            "sudo systemctl restart '${APP_SERVICE_NAME}.service' || echo 'Service not found; continuing...'"
